[package]
name = "code"
version = "0.1.0"
authors = ["Phil Fried <philipsfried@gmail.com>", "Daan van Berkel <daan.v.berkel.1980@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
